
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Attribute
{

    public Attribute()
    {

        this.AttributeValues = new HashSet<AttributeValue>();

    }


    public int AttributeID { get; set; }

    public string Name { get; set; }

    public int controlType_id { get; set; }

    public int webstore_id { get; set; }

    public bool applyToAllProducts { get; set; }

    public bool applyToCategory { get; set; }

    public System.DateTime InsertDate { get; set; }

    public int InsertENTUserAccountId { get; set; }

    public System.DateTime UpdateDate { get; set; }

    public int UpdateENTUserAccountId { get; set; }

    public byte[] Version { get; set; }



    public virtual controlType controlType { get; set; }

    public virtual ICollection<AttributeValue> AttributeValues { get; set; }

}

}
