
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class controlType
{

    public controlType()
    {

        this.Attributes = new HashSet<Attribute>();

    }


    public int controlType_id { get; set; }

    public string controlName { get; set; }



    public virtual ICollection<Attribute> Attributes { get; set; }

}

}
