
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class customer
{

    public int customer_id { get; set; }

    public int webstore_id { get; set; }

    public string fname { get; set; }

    public string lname { get; set; }

    public string address1 { get; set; }

    public string address2 { get; set; }

    public string city { get; set; }

    public string region { get; set; }

    public string zip { get; set; }

    public string country { get; set; }

    public string shippingRegion { get; set; }

    public Nullable<decimal> dayPhone { get; set; }

    public Nullable<decimal> cellPhone { get; set; }

    public Nullable<decimal> evePhone { get; set; }

    public string creditCard { get; set; }

    public string username { get; set; }

    public string password { get; set; }

    public string email { get; set; }

    public string squestion { get; set; }

    public string sanswer { get; set; }

    public bool sendEmail { get; set; }

    public Nullable<int> fbId { get; set; }

    public Nullable<int> rewardPoints { get; set; }

}

}
