
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class MenuItem
{

    public int MenuItemId { get; set; }

    public string MenuItemName { get; set; }

    public string Description { get; set; }

    public string Url { get; set; }

    public Nullable<int> ParentMenuItemId { get; set; }

    public byte DisplaySequence { get; set; }

    public bool IsAlwaysEnabled { get; set; }

    public int webstore_id { get; set; }

    public bool Admin { get; set; }

}

}
