
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public int OrderID { get; set; }

    public int product_id { get; set; }

    public string ProductName { get; set; }

    public int Quantity { get; set; }

    public decimal UnitCost { get; set; }

    public Nullable<decimal> Subtotal { get; set; }



    public virtual Order Order { get; set; }

    public virtual product product { get; set; }

}

}
