
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class pcategory
{

    public pcategory()
    {

        this.pcategory1 = new HashSet<pcategory>();

        this.pcategoryproducts = new HashSet<pcategoryproduct>();

    }


    public int Id { get; set; }

    public Nullable<int> ParentId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Nullable<int> WebstoreId { get; set; }



    public virtual ICollection<pcategory> pcategory1 { get; set; }

    public virtual pcategory pcategory2 { get; set; }

    public virtual ICollection<pcategoryproduct> pcategoryproducts { get; set; }

}

}
