
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class pcategoryproduct
{

    public int Id { get; set; }

    public Nullable<int> pcategoryFK { get; set; }

    public Nullable<int> productFK { get; set; }



    public virtual product product { get; set; }

    public virtual pcategory pcategory { get; set; }

}

}
