
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class product
{

    public product()
    {

        this.OrderDetails = new HashSet<OrderDetail>();

        this.menuReviews = new HashSet<menuReview>();

        this.ProductAttributeValues = new HashSet<ProductAttributeValue>();

        this.ShoppingCarts = new HashSet<ShoppingCart>();

        this.pcategoryproducts = new HashSet<pcategoryproduct>();

        this.productcategories = new HashSet<productcategory>();

        this.Pictures = new HashSet<Picture>();

    }


    public int product_id { get; set; }

    public int webstore_id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public decimal price { get; set; }

    public string thumbnail { get; set; }

    public string image { get; set; }

    public bool promofront { get; set; }

    public bool promodept { get; set; }

    public bool defaultAttribute { get; set; }

    public bool defaultAttCat { get; set; }

    public System.DateTime InsertDate { get; set; }

    public int InsertENTUserAccountId { get; set; }

    public System.DateTime UpdateDate { get; set; }

    public int UpdateENTUserAccountId { get; set; }

    public byte[] Version { get; set; }

    public Nullable<bool> IsSpecial { get; set; }



    public virtual ICollection<OrderDetail> OrderDetails { get; set; }

    public virtual ICollection<menuReview> menuReviews { get; set; }

    public virtual ICollection<ProductAttributeValue> ProductAttributeValues { get; set; }

    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }

    public virtual ICollection<pcategoryproduct> pcategoryproducts { get; set; }

    public virtual ICollection<productcategory> productcategories { get; set; }

    public virtual ICollection<Picture> Pictures { get; set; }

}

}
