
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class SocialMedia
{

    public int Id { get; set; }

    public Nullable<int> WebstoreId { get; set; }

    public string Facebook { get; set; }

    public string Twitter { get; set; }

    public string Google { get; set; }

    public string LinkedIn { get; set; }

    public string AddThis { get; set; }

}

}
