
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class state
{

    public state()
    {

        this.cities = new HashSet<city>();

    }


    public int idState { get; set; }

    public string stateSname { get; set; }

    public string stateLname { get; set; }



    public virtual ICollection<city> cities { get; set; }

}

}
