
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace seoWebApplication.Data
{

using System;
    using System.Collections.Generic;
    
public partial class vw_attribute_values
{

    public string Name { get; set; }

    public int AttributeValueID { get; set; }

    public int controlType_id { get; set; }

    public int webstore_id { get; set; }

    public string Value { get; set; }

    public int AttributeID { get; set; }

    public bool applyToAllProducts { get; set; }

}

}
